version: '3'

services:
  cassandra:
    image: cassandra
    container_name: cassandra
    volumes:
      - '${PWD}/docker/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml'
    ports:
      - '9042:9042'
  sqs:
    image: localstack/localstack
    container_name: sqs
    ports:
      - "4567-4584:4567-4584"
      - "8090:8080"
    environment:
      - SERVICES=sqs
  tp:
    build:
      context: .
    environment:
      - FOO=bar
