version: '3.3'

services:
  backend:
    container_name: backend
    image: backend
    environment:
      - CASSANDRA_HOST=cassandra
      - SQS_HOST=http://sqs:4576
      - PROFILE_ENV=prod
    ports:
      - "8070:8080"
    command: "bash -c './wait.sh -t 30 sqs:4576 && ./wait.sh -t 30 cassandra:9042 && /app/backend'"
  frontend:
    container_name: frontend
    image: frontend
    ports:
      - "8080:80"
  sqs:
    image: localstack/localstack
    container_name: sqs
    ports:
      - "8090:8080"
    environment:
      - SERVICES=sqs
  cassandra:
    image: cassandra
    container_name: cassandra
    volumes:
      - '${PWD}/docker/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml'
