version: '3'

services:
  cassandra:
    image: cassandra
    container_name: cassandra
    volumes:
      - '${PWD}/docker/cassandra/cassandra.yaml:/etc/cassandra/cassandra.yaml'
    ports:
      - '9042:9042'
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5
  sqs:
    image: localstack/localstack
    container_name: sqs
    ports:
      - "4567-4584:4567-4584"
      - "8090:8080"
    environment:
      - SERVICES=sqs
  tp:
    container_name: track_progress
    image: track-progress:1.0.0
    environment:
      - CASSANDRA_HOST=cassandra
      - SQS_HOST=http://sqs:4576
    depends_on: 
      - cassandra
      - sqs
