[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.4"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.5.1"

[[constraint]]
  name = "github.com/gocql/gocql"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.30.14"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.5.0"
